# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/productivity_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*